<div class="row">
    <div class="col-xs-12 col-sm-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Danh sách file excel trên máy chủ</h3>
            </div>
            <div class="panel-body">
                <table class="table table-hover table-striped table-condensed">
                    <tr>
                        <th>File name</th>
                        <th>Download</th>
                    </tr>
                    <?php foreach (glob('Data/*.xlsx') as $filename) : ?>
                    <tr>
                        <td>
                            <a href="?file=<?php echo $filename; ?>">
                                <?php echo $filename; ?>
                            </a>
                        </td>
                        <td>
                            <a href="?file=<?php echo $filename; ?>&download=1" target="_blank">
                                <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
                            </a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6">
        <form class="panel panel-info" method="post" action="" enctype="multipart/form-data">
            <div class="panel-heading">
                <label class="panel-title" for="exampleInputFile">Tải lên:</label>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <input type="file" id="fileToUpload" name="fileToUpload">
                    <p class="help-block">Chọn file excel để tải lên.</p>
                </div>
            </div>
            <div class="panel-footer">
                <button type="submit" name="fileUploaded" value="ok" class="btn btn-default">Tải lên</button>
            </div>
        </form>
    </div>
</div>
